build:
  maxIssues: 0

config:
  validation: true

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    active: false
